language : python

install:
  - pip install -r requirements.txt
  - pip install python-coveralls
  - pip install coverage      
  - pip install nose  
  - pip install codeclimate-test-reporter
# command to run tests
script:
  - nosetests --with-coverage tests/events_tests.py
  - nosetests --with-coverage tests/users_tests.py

after_success:  
  - coveralls
  - coverage report
