language : python
python:
    - "3.6"


install:
  - pip install -r requirements.txt
  - pip install python-coveralls
  - pip install coverage
  - pip install nose
  - pip install codeclimate-test-reporter

env:
  global:
      - DATABASE_URL=postgres://localhost:5433/test_db

script:
  - nosetests --rednose tests/test_events.py tests/test_users.py --nocapture --with-coverage

services:
  - postgresql
before_script:
  - psql -c 'create database test_db;' -U postgres


after_success:
  - coveralls
  - codeclimate-test-reporter --file .coverage