"""empty message

Revision ID: 06586e230e3b
Revises: 130059d82bbd
Create Date: 2017-12-14 22:28:58.691879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06586e230e3b'
down_revision = '130059d82bbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rsvps',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'event_id')
    )
    op.drop_table('subscriptions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id'], ['events.id'], name='subscriptions_id_fkey')
    )
    op.drop_table('rsvps')
    # ### end Alembic commands ###
