"""empty message

Revision ID: 130059d82bbd
Revises: f0548bda7e48
Create Date: 2017-12-14 22:23:48.512846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '130059d82bbd'
down_revision = 'f0548bda7e48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'events', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'events', type_='unique')
    # ### end Alembic commands ###
