"""empty message

Revision ID: 193c5a58430a
Revises: 3d2eb82403f1
Create Date: 2018-04-08 00:11:50.915399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '193c5a58430a'
down_revision = '3d2eb82403f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'image')
    # ### end Alembic commands ###
